### ISSUE TITLE
adding requirement.txt to reproduce codes

### ISSUE THREAD

**Issue by lingjie00** [jasonzy121/Deep_Learning_Asset_Pricing#1]
Hi Jason, thank you for sharing the codes and I'm very interested in exploring your thesis paper.

I'm trying to reproduce the results you have, following instructions listed in README. Something I found to be missing is the dependencies.

I have followed the instructions and found the following libraries essential. If possible perhaps we could add in the version you used during development as well.

```
tensorflow==1.12.0
tensorflow-gpu==1.12.0
jupyter
seaborn
statsmodels
scikit-learn
```

I'm currently at `Step 1: Training the SDF network` and will add in more dependencies if needed.

I can initiate a PR if that would be easier.

**Comment by jasonzy121** [comment]
Thanks for your suggestion! I have added the requirements.txt file
