### ISSUE TITLE
About SDF

### ISSUE THREAD

**Issue by Ed-Chai** [jasonzy121/Deep_Learning_Asset_Pricing#2]
Excuse me, why M=1-sum(WR) in the paper while in the code implementation M=1+sum(WR) ？

**Comment by jasonzy121** [comment]
Sorry for the confusion, this is a small inconsistency from an early draft of the paper, and you can think of w in code here is equivalent to -w in the paper

**Comment by Ed-Chai** [comment]
Thank you very much! 
Because I am new in this domain, some questions confusing me a lot! 
In step3, why could we generate RF=R*F*50? What's the meaning of multipling 50?
And why could we approximate R*F*50 in step4 to get estimation of beta，and why could we use beta as weight to construct a long-short portfolio to calcultate sharpe ratio? I remember in factor model, weight=(beta.T.dot(beta))^-1.dot(beta.T).
step5: why could we to get predictive R_t as beta_t.dot(R_t)/w_t.dot(w_t)*w_t?
